site_name: 'yichen的信安知识库'
copyright: "Copyright &copy; 2019 - 2024 yichen"
site_url:  "https://yichen115.github.io/"
site_author: "yichen"
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  language: 'zh'
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    #- toc.integrate # 右侧生产目录
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 

plugins:
  - search

markdown_extensions:
  - toc:
      baselevel: 2  # 默认一级目录为二级目录，方便右侧显示
  - attr_list
  - md_in_html
  - nl2br


extra_css:
  - extra.css # 自定义CSS
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css